// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGFyur1TXXH92gdVbYtZM50RInssP6woI',
    appId: '1:931659892726:web:4f5766bfd9a844806ce9d7',
    messagingSenderId: '931659892726',
    projectId: 'tp-m-ipscb-cacc6',
    authDomain: 'tp-m-ipscb-cacc6.firebaseapp.com',
    storageBucket: 'tp-m-ipscb-cacc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYL_LiiOCVnhyWJTPCkAqQZ67aC_sJwQI',
    appId: '1:931659892726:android:b9eb85f07eb44ab26ce9d7',
    messagingSenderId: '931659892726',
    projectId: 'tp-m-ipscb-cacc6',
    storageBucket: 'tp-m-ipscb-cacc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqPvjq-sqR_lf3OWvANAfTEES1J6yeDo',
    appId: '1:931659892726:ios:13e08fb880f677726ce9d7',
    messagingSenderId: '931659892726',
    projectId: 'tp-m-ipscb-cacc6',
    storageBucket: 'tp-m-ipscb-cacc6.appspot.com',
    iosBundleId: 'com.example.tpMIpscb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqPvjq-sqR_lf3OWvANAfTEES1J6yeDo',
    appId: '1:931659892726:ios:13e08fb880f677726ce9d7',
    messagingSenderId: '931659892726',
    projectId: 'tp-m-ipscb-cacc6',
    storageBucket: 'tp-m-ipscb-cacc6.appspot.com',
    iosBundleId: 'com.example.tpMIpscb',
  );
}
